name: exhibition_booth_app
description: Exhibition Booth Reservation (starter)
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^7.0.0
  flutter_riverpod: ^2.3.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7

  sqflite: ^2.2.8
  path_provider: ^2.1.2
  path: ^1.8.3

  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/logo.svg
    - assets/svg/expo1.svg
    - assets/svg/expo2.svg

# ðŸ”’ Force modern Android plugin to avoid v1 Registrar crash
dependency_overrides:
  path_provider_android: 2.2.22
